# Generated by Django 4.1.3 on 2022-11-28 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipv4Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('root', models.CharField(max_length=200)),
                ('db', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geoname_id', models.CharField(max_length=200)),
                ('locale_code', models.CharField(max_length=200)),
                ('continent_code', models.CharField(max_length=200)),
                ('continent_name', models.CharField(max_length=200)),
                ('country_iso_code', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('is_in_european_union', models.BooleanField()),
            ],
        ),
    ]
