# Generated by Django 4.1.3 on 2022-11-28 00:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('geoip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('address_list_prefix', models.CharField(default='geoip', max_length=9)),
                ('timeout', models.CharField(default='7d', max_length=200)),
                ('location', models.ManyToManyField(to='geoip.location')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.router')),
            ],
        ),
    ]
