# Generated by Django 4.1.3 on 2022-11-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0002_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
