# Generated by Django 4.1.3 on 2022-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0003_alter_combo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
