# Generated by Django 4.1.3 on 2022-12-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0005_alter_combo_address_list_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
