# Generated by Django 4.1.3 on 2022-11-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
