# Generated by Django 4.1.3 on 2022-11-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_consumer_description_alter_consumer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.consumer'),
        ),
    ]
