# Generated by Django 4.1.3 on 2022-11-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_router_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.consumer'),
        ),
    ]
