# Generated by Django 4.1.3 on 2022-11-28 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoip', '0002_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('every_minute', models.CharField(default='0', max_length=200)),
                ('every_hour', models.CharField(default='0', max_length=200)),
                ('every_day', models.CharField(default='0', max_length=200)),
                ('every_week', models.CharField(default='0', max_length=200)),
                ('every_month', models.CharField(default='0', max_length=200)),
                ('next_run', models.DateTimeField()),
                ('combo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geoip.combo')),
            ],
        ),
    ]
