# Generated by Django 4.1.3 on 2022-11-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_task_next_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_run',
            field=models.DateTimeField(null=True),
        ),
    ]
