# Generated by Django 4.1.3 on 2022-11-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_task_next_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='next_run',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
