# Generated by Django 4.1.3 on 2022-11-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_task_next_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='next_run',
        ),
    ]
