# Generated by Django 4.1.3 on 2022-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_remove_task_next_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='every_day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='every_hour',
        ),
        migrations.RemoveField(
            model_name='task',
            name='every_minute',
        ),
        migrations.RemoveField(
            model_name='task',
            name='every_month',
        ),
        migrations.RemoveField(
            model_name='task',
            name='every_week',
        ),
        migrations.AddField(
            model_name='task',
            name='freq_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='freq_type',
            field=models.CharField(default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='time_of_day',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
    ]
