# Generated by Django 4.1.3 on 2022-11-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0002_combo'),
        ('scheduler', '0006_remove_task_every_day_remove_task_every_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoip.combo'),
        ),
    ]
