# Generated by Django 4.1.3 on 2022-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_task_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='freq_type',
            field=models.CharField(help_text='Could be: O(once), D(aily), M(ontly), W(eekly)', max_length=1),
        ),
    ]
