# Generated by Django 4.1.3 on 2022-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_task_freq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='freq_interval',
            field=models.IntegerField(help_text='D=Interval, W=0 to 7, M=1 to [28,30,31]'),
        ),
        migrations.AlterField(
            model_name='task',
            name='freq_type',
            field=models.CharField(help_text='Could be: O(once), D(aily), W(eekly), M(ontly)', max_length=1),
        ),
    ]
