# Generated by Django 4.1.3 on 2022-11-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0002_combo'),
        ('scheduler', '0013_alter_task_freq_interval_alter_task_freq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='combo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geoip.combo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='freq_interval',
            field=models.IntegerField(help_text='D=Interval, W=0 to 7, M=1 to 31'),
        ),
        migrations.AlterField(
            model_name='task',
            name='freq_type',
            field=models.CharField(help_text='O(nce), D(aily), W(eekly), M(ontly)', max_length=1),
        ),
    ]
