# Generated by Django 4.1.3 on 2022-11-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('scheduler', '0014_alter_task_combo_alter_task_freq_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
