# Generated by Django 4.1.3 on 2022-11-30 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0005_alter_combo_address_list_prefix'),
        ('scheduler', '0015_setup_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='combo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='geoip.combo'),
        ),
    ]
